# This file is part of the asdicts.
#
# Copyright (c) 2021 Serghei Iakovlev
#
# For the full copyright and license information, please view
# the LICENSE file that was distributed with this source code.

codecov:
  notify:
    # will no delay sending notifications until all ci is finished
    require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "65...90"

  status:
    project:
      default:
        # the amount that coverage can drop while still posting a success
        threshold: 1%
    patch: no
    changes: no

ignore:
  - "*.yml"
  - "*.rst"
  - "*.mk"
  - "*.txt"
  - "*.in"
  - ".coveragerc"
  # ignore folders and all its contents
  - ".git/.*"
  - ".github/.*"
  - ".pytest_cache/.*"
  - "__pycache__/.*"
  - "build/.*"
  - "dist/.*"
  - "*.egg-info/.*"
  - "htmlcov/.*"
  - "tests/.*"
