# This file is part of the asdicts.
#
# Copyright (c) 2021 Serghei Iakovlev
#
# For the full copyright and license information, please view
# the LICENSE file that was distributed with this source code.

name: CI

on:
  push:
    branches:
      - master
      - 'v[0-9]+.[0-9]+.x'
      - 'feature/**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

  pull_request:
    branches:
      - master
      - 'v[0-9]+.[0-9]+.x'
env:
  PYTHON: python

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: Python ${{ matrix.python }} on ${{ matrix.os }}

    # The maximum number of minutes to let a workflow run
    # before GitHub automatically cancels it. Default: 360
    timeout-minutes: 30

    strategy:
      # When set to true, GitHub cancels
      # all in-progress jobs if any matrix job fails.
      fail-fast: false

      matrix:
        python: [ '3.6', '3.7', '3.8', '3.9', '3.10', '3.10' ]
        os: [ ubuntu-lates, macos-latest, windows-latest ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 5

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Makefile selftest
        run: make help

      - name: Install dependencies
        run: make install

      - name: Minimal load test
        run: |
          case ${{ runner.os }} in
            Windows*)
              source .venv/Scripts/activate ;;
            *)
              source .venv/bin/activate ;;
          esac

          python -c "import asdicts; print(asdicts.__version__)"

      - name: Run unit tests with coverage
        run: make test

      - name: Success Reporting
        if: success()
        run: git log --format=fuller -5

  lint:
    runs-on: ubuntu-20.04
    name: Code linting

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: make init

      - name: Code linting
        run: make lint

  package:
    runs-on: ubuntu-latest
    name: Build & verify package

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: make init

      - name: Testing package distribution and installation
        run: make test-dist
